language: csharp
mono: none
dotnet: 2.1.104

script:
	- dotnet restore
	- dotnet build
	- dotnet test PrimeService.Tests

notifications:
  email:
    recipients:
      - benno.green@gmail.com
    on_success: never #default: change
    on_failure: never #default: always